### ISSUE TITLE
How can we stop pose Detection? 

### ISSUE THREAD

**Issue by Saqib92** [fustyles/webduino#7]
How can we stop Pose Detection and remove skeleton from Video without stopping video. and then re add it?

**Comment by fustyles** [comment]
> How can we stop Pose Detection and remove skeleton from Video without stopping video. and then re add it?

Hi, which code did you use?

**Comment by Saqib92** [comment]
> > How can we stop Pose Detection and remove skeleton from Video without stopping video. and then re add it?
> 
> Hi, which code did you use?

https://github.com/fustyles/webduino/blob/master/TensorFlow/PoseDetection_video/PoseDetection_video_multi.html

**Comment by fustyles** [comment]
> > > How can we stop Pose Detection and remove skeleton from Video without stopping video. and then re add it?
> > 
> > 
> > Hi, which code did you use?
> 
> https://github.com/fustyles/webduino/blob/master/TensorFlow/PoseDetection_video/PoseDetection_video_multi.html

Sorry for the late reply. I modified the code to implement the function.

**Comment by Saqib92** [comment]
> > > > How can we stop Pose Detection and remove skeleton from Video without stopping video. and then re add it?
> > > 
> > > 
> > > Hi, which code did you use?
> > 
> > 
> > https://github.com/fustyles/webduino/blob/master/TensorFlow/PoseDetection_video/PoseDetection_video_multi.html
> 
> Sorry for the late reply. I modified the code to implement the function.

Just checked. it working fine. will add in my code.
